FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y postgresql-client imagemagick

WORKDIR /app

RUN gem install bundler

ENV BUNDLE_GEMFILE=/app/Gemfile \
  BUNDLE_JOBS=20 \
  BUNDLE_PATH=/bundle \
  BUNDLE_BIN=/bundle/bin \
  GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"

COPY Gemfile Gemfile.lock ./

RUN bundle install

CMD ["bash"]
