services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    # ports:
    #   - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:7.2.0
    # ports:
    #   - "6379:6379"
    volumes:
      - 'redis:/data'
  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    # ports:
    #   - '${DOCKER_HOST_WEB_PORT:-3000}:3000'
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
      - '.env:/app/.env'
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
  web:
    depends_on:
      - 'app'
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - './public:/app/public'
      - './log:/app/log'
    ports:
      - '80:80'
  worker:
    depends_on:
      - 'app'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.development
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
      - '.env:/app/.env'
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  redis:
  postgres:
  bundle_cache:
